# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5w42FXEn9GCciJMXdenneniDsKP0Ja2
"""

import pandas as pd

# loading json file
file_path = "/content/data/trends_20260409.json"

df = pd.read_json(file_path)

print("Loaded", len(df), "stories from", file_path)

# removing duplicates
df = df.drop_duplicates(subset=["post_id"])
print("After removing duplicates:", len(df))

# removing missing values
df = df.dropna(subset=["post_id", "title", "score"])
print("After removing nulls:", len(df))

# converting data types
df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

# removing low score stories
df = df[df["score"] >= 5]
print("After removing low scores:", len(df))

# removing extra spaces in title
df["title"] = df["title"].str.strip()

# saving cleaned data
output_file = "/content/data/trends_cleaned.csv"

df.to_csv(output_file, index=False)

print("\nSaved", len(df), "rows to", output_file)

print("\nStories per category:")
print(df["category"].value_counts())