# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BtcGB927sVpU1yGAOvTkodSSnVyRuyP9
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

# loading analysed data
df = pd.read_csv("/content/trends_analysed.csv")

# creating outputs folder
os.makedirs("outputs", exist_ok=True)

print("Data loaded and outputs folder ready")

# getting top 10 stories by score
top10 = df.sort_values(by="score", ascending=False).head(10)

# shorten long titles
titles = top10["title"].apply(lambda x: x[:50] + "..." if len(x) > 50 else x)

plt.figure()

plt.barh(titles, top10["score"])
plt.xlabel("Score")
plt.ylabel("Story Title")
plt.title("Top 10 Stories by Score")

plt.gca().invert_yaxis()  # highest at top

# saving chart
plt.savefig("outputs/chart1_top_stories.png")
plt.show()

# counting stories per category
category_counts = df["category"].value_counts()

plt.figure()

plt.bar(category_counts.index, category_counts.values)
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Stories per Category")

# saving chart
plt.savefig("outputs/chart2_categories.png")
plt.show()

plt.figure()

# separate popular and non-popular
popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

# scatter plot
plt.scatter(popular["score"], popular["num_comments"], label="Popular")
plt.scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")

plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Comments")

plt.legend()

# saving chart
plt.savefig("outputs/chart3_scatter.png")
plt.show()

fig, axs = plt.subplots(1, 3, figsize=(18, 5))

# Chart 1
axs[0].barh(titles, top10["score"])
axs[0].set_title("Top Stories")
axs[0].invert_yaxis()

# Chart 2
axs[1].bar(category_counts.index, category_counts.values)
axs[1].set_title("Categories")

# Chart 3
axs[2].scatter(popular["score"], popular["num_comments"], label="Popular")
axs[2].scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")
axs[2].set_title("Score vs Comments")
axs[2].legend()

# overall title
plt.suptitle("TrendPulse Dashboard")

# saving dashboard
plt.savefig("outputs/dashboard.png")
plt.show()