# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C1vGXpVg3DT9k1E32JhfUbog3HfsKXEW
"""

import pandas as pd
import numpy as np

# loading cleaned csv file
df = pd.read_csv("/content/data/trends_cleaned.csv")

print("Loaded data:", df.shape)

# printing first 5 rows
print("\nFirst 5 rows:")
print(df.head())

# average values
print("\nAverage score:", df["score"].mean())
print("Average comments:", df["num_comments"].mean())

# converting to numpy arrays
scores = df["score"].to_numpy()
comments = df["num_comments"].to_numpy()

print("\n--- NumPy Stats ---")

# mean, median, std
print("Mean score:", np.mean(scores))
print("Median score:", np.median(scores))
print("Std deviation:", np.std(scores))

# max and min
print("Max score:", np.max(scores))
print("Min score:", np.min(scores))

# category with most stories
top_category = df["category"].value_counts().idxmax()
count = df["category"].value_counts().max()

print("\nMost stories in:", top_category, f"({count} stories)")

# most commented story
top_comment_row = df.loc[df["num_comments"].idxmax()]

print("\nMost commented story:")
print(top_comment_row["title"], "-", top_comment_row["num_comments"], "comments")

# adding engagement column
df["engagement"] = df["num_comments"] / (df["score"] + 1)

# add is_popular column
avg_score = df["score"].mean()
df["is_popular"] = df["score"] > avg_score

# saving new csv
output_file = "data/trends_analysed.csv"
df.to_csv(output_file, index=False)

print("\nSaved to", output_file)