# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0bKh9_EgwhAEAAZvKUml5wPyHB6ZgTH
"""

import pandas as pd

df = pd.read_csv("data/trends_cleaned.csv")

print("\nPosts per category:")
print(df["category"].value_counts())

print("\nAverage score per category:")
print(df.groupby("category")["score"].mean())

print("\nTop scoring post:")
print(df.sort_values(by="score", ascending=False).head(1))