# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108IXtO3LxNjlPsTMviAcePD2kOGUIWhT
"""

import requests
import json
import time
import os
from datetime import datetime

BASE_URL = "https://hacker-news.firebaseio.com/v0"
HEADERS = {"User-Agent": "TrendPulse/1.0"}

CATEGORIES = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

MAX_PER_CATEGORY = 25

def get_top_ids():
    try:
        res = requests.get(BASE_URL + "/topstories.json", headers=HEADERS)
        return res.json()[:500]
    except:
        return []

def get_story(id):
    try:
        res = requests.get(f"{BASE_URL}/item/{id}.json", headers=HEADERS)
        return res.json()
    except:
        return None

def get_category(title):
    title = title.lower()
    for cat in CATEGORIES:
        for word in CATEGORIES[cat]:
            if word in title:
                return cat
    return None

def main():
    ids = get_top_ids()
    results = []
    count = {c: 0 for c in CATEGORIES}

    for cat in CATEGORIES:
        for id in ids:
            if count[cat] >= MAX_PER_CATEGORY:
                break

            story = get_story(id)
            if not story:
                continue

            title = story.get("title", "")

            if get_category(title) == cat:
                results.append({
                    "post_id": story.get("id"),
                    "title": title,
                    "category": cat,
                    "score": story.get("score", 0),
                    "num_comments": story.get("descendants", 0),
                    "author": story.get("by", "unknown"),
                    "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                })

                count[cat] += 1

        time.sleep(2)

    os.makedirs("data", exist_ok=True)
    filename = "data/trends_" + datetime.now().strftime("%Y%m%d") + ".json"

    with open(filename, "w") as f:
        json.dump(results, f, indent=4)

    print("Collected", len(results), "stories")

if __name__ == "__main__":
    main()