# -*- coding: utf-8 -*-
"""task2_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W17bgYt20uh3uSuDR9Nl_ch1rMnpHA38
"""

import pandas as pd

df = pd.read_json("data/trends_20260408.json")
df.drop_duplicates(inplace=True)
df.dropna(subset=["title"], inplace=True)

df["author"].fillna("unknown", inplace=True)
df["score"].fillna(0, inplace=True)
df["num_comments"].fillna(0, inplace=True)

df.to_csv("data/trends_cleaned.csv", index=False)

print("Cleaned CSV saved")