# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Aj9dGAGiemUOd14SZHAPjg-k9yIOfTU
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("data/trends_cleaned.csv")

df["category"].value_counts().plot(kind="bar")
plt.title("Posts per Category")
plt.xlabel("Category")
plt.ylabel("Count")
plt.show()

df["category"].value_counts().plot(kind="pie", autopct="%1.1f%%")
plt.title("Category Distribution")
plt.show()